// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwlA-8hgR2STIm-ezqVW-5AVeFjQy_Q-E',
    appId: '1:1042592806847:android:0d5e29d36e1b9a123d530a',
    messagingSenderId: '1042592806847',
    projectId: 'blissfullmassage-4d0ec',
    storageBucket: 'blissfullmassage-4d0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_bO6GEdaUBXTvAbrTf9a0dEHyfA_g5o',
    appId: '1:1042592806847:ios:6db84557ea7e88043d530a',
    messagingSenderId: '1042592806847',
    projectId: 'blissfullmassage-4d0ec',
    storageBucket: 'blissfullmassage-4d0ec.firebasestorage.app',
    iosBundleId: 'com.example.blissfulmassage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmV96dFGEleHEy9NbnpUVQHsYOGJUuPkE',
    appId: '1:1042592806847:web:1cc94ac3a098410d3d530a',
    messagingSenderId: '1042592806847',
    projectId: 'blissfullmassage-4d0ec',
    authDomain: 'blissfullmassage-4d0ec.firebaseapp.com',
    storageBucket: 'blissfullmassage-4d0ec.firebasestorage.app',
    measurementId: 'G-2G0QRRXGNX',
  );
}
